--
-- Table structure for table `us_citizens`
--

DROP TABLE IF EXISTS US_CITIZENS;
CREATE TABLE US_CITIZENS (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_CITY INT NOT NULL,
    ID_STATE INT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    MARRIED BOOLEAN NOT NULL,
    SSN VARCHAR(11) NOT NULL,
    INCOME DECIMAL(12, 2) NOT NULL,
    CITIZENSHIP VARCHAR(10) NOT NULL DEFAULT 'US',
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CITY) REFERENCES US_CITIES(ID),
    FOREIGN KEY (ID_STATE) REFERENCES US_STATES(ID)
);

-- 
-- After this, you can run the script to insert citizens into the database
--